
comment('Executing ASIUA:Licenses/Business/Sexually Oriented Business/*');
showMessage=true;
// DISABLED: ASIUA:Licenses/Business/Sexually Oriented Business/*:2
// if (proximity('AGIS_CHARCO', 'Sexually Orientated Businesses', 3000)) {
// 	addAppCondition('CC PERMIT', 'Applied', 'SOB Hold', 'The SOB being applied for may be within 3000 feet of an existing SOB. Further review is needed.', 'Hold');
// 	}

