
showMessage=true;
showDebug=true;
comment('Building Final...processing branch');
// DISABLED: BldgFee:10
// comment(inspType + ' checking for fees...$' + myfeeAmountExcept(capId));
// DISABLED: BldgFee:15
// if ((myfeeAmountExcept(capId) > 0)) {
// 	comment('Inspection cannot be scheduled because there is a balance of $' + myfeeAmountExcept(capId) + ' due on this permit.');
// 	cancel = true;
// 	}

