
// DISABLED: CC_050_AppSubmitAfter:1
// if (appMatch('Building/*/*/*')) {
// 	br_nch('CC_051_BLD_AppSubmitAfter');
// 	}

// DISABLED: CC_050_AppSubmitAfter:2
// if (appMatch('Licenses/*/*/*')) {
// 	br_nch('CC_051_LIC_AppSubmitAfter');
// 	}

// DISABLED: CC_050_AppSubmitAfter:3
// if (appMatch('Planning/Managed Growth/*/*')) {
// 	br_nch('CC_051_GM_AppSubmitAfter');
// 	}

// DISABLED: CC_050_AppSubmitAfter:4
// if (appMatch('Planning/Land Development/*/*')) {
// 	br_nch('CC_051_LD_AppSubmitAfter');
// 	}

// DISABLED: CC_050_AppSubmitAfter:5
// if (appMatch('CodeEnforcement/*/*/*')) {
// 	br_nch('CC_051_CE_AppSubmitAfter');
// 	}

// DISABLED: CC_050_AppSubmitAfter:6
// copyParcelGisObjects();

