
// DISABLED: CC_352_BLD_WFUpdateAfter:1
// if (AInfo['District'] = 'Charlotte County Sanitation District') {
// 	distFee = lookup('CC_CHAR_CO_SAN_DIST',monCurrent);
// 	updateFee('GARB-CC',feeSch,'Assessed at Issuance',distFee,'Y');
// 	}

// DISABLED: CC_352_BLD_WFUpdateAfter:2
// if (AInfo['District'] = 'Don Pedro/Knight Island Sanitation District') {
// 	distFee = lookup('CC_DPKI_SAN_DIST',monCurrent);
// 	updateFee('GARB-DP',feeSch,'Assessed at Issuance',distFee,'Y');
// 	}

