
// DISABLED: CC_351_BLD_WFUpdateAfter:1
// monCurrent = sysDate.getMonth();
// DISABLED: CC_351_BLD_WFUpdateAfter:2
// if (appMatch('Building/Construction/Commercial/Multi-Family') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_COM_MU';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_351_BLD_WFUpdateAfter:3
// if (appMatch('Building/Construction/Residential/Duplex') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_RES_DU';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_351_BLD_WFUpdateAfter:4
// if (appMatch('Building/Construction/Residential/Single Family') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_RES_SF';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_351_BLD_WFUpdateAfter:5
// if (appMatch('Building/Construction/Residential/Townhouse') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_RES_TWNHS';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_351_BLD_WFUpdateAfter:6
// if (appMatch('Building/Construction/Residential/DCA-Home') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_RES_TWNHS';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_351_BLD_WFUpdateAfter:7
// if (appMatch('Building/Construction/Residential/Mobile Home') && wfTask == 'Permit Issuance' && wfStatus == 'Issued' && !balanceDue == 0) {
// 	feeSch = 'BLD_CON_RES_TWNHS';
// 	br_nch('CC_352_BLD_WFUpdateAfter');
// 	}

