
// DISABLED: CC_301_LD_WFUpdateBefore:1
// comment('CC_301_LD_WFUpdateBefore Executing message');
// DISABLED: CC_301_LD_WFUpdateBefore:2
// if (appMatch('Planning/Land Development/Storm Water/*') && wfTask == 'Review' && wfStatus == 'Approved' && !balanceDue == 0) {
// 	showDebug = false;
// 	showMessage = false;
// 	message='All Fees must be paid before this action can take place.';
// 	showMessage = true;
// 	}

