
// DISABLED: CC_301_GM_WFUpdateBefore:1
// comment('CC_301_GM_WFUpdateBefore Executing message');
// DISABLED: CC_301_GM_WFUpdateBefore:2
// if (appMatch('Planning/Growth Mgmt/Zoning Permits/*') && wfTask == 'Finaled' && wfStatus == ['C of O Issued','C of Completion Issued'] && !balanceDue == 0) {
// 	showDebug = false;
// DISABLED: CC_301_GM_WFUpdateBefore:3
// 	showMessage = false;
// 	message='All Fees must be paid before this action can take place.';
// 	showMessage = true;
// 	}

// DISABLED: CC_301_GM_WFUpdateBefore:4
// if (appMatch('Planning/Growth Mgmt/DRC/*') && wfTask == 'Finaled' && wfStatus == ['Approved with Conditions','Approved'] && !balanceDue == 0) {
// 	showDebug = false;
// DISABLED: CC_301_GM_WFUpdateBefore:5
// 	showMessage = false;
// 	message='All Fees must be paid before this action can take place.';
// 	showMessage = true;
// 	}

