
// DISABLED: PaymentApplyAfter:1
// if (currentUserID == 'LAPHAMK') {
// 	showMessage=true;
// 	showDebug = true;
//	} else {
// 	showMessage=false;
// 	showDebug = false;
// 	}

// DISABLED: PaymentApplyAfter:2
// br_nch('PAA:' + appTypeArray[0] + '/*/*/*');
// DISABLED: PaymentApplyAfter:3
// br_nch('PAA:' + appTypeArray[0] + '/' + appTypeArray[1] + '/*/*');
// DISABLED: PaymentApplyAfter:4
// br_nch('PAA:' + appTypeArray[0] + '/' + appTypeArray[1] + '/' + appTypeArray[2] + '/*');
// DISABLED: PaymentApplyAfter:5
// br_nch('PAA:' + appTypeString);
// DISABLED: PaymentApplyAfter:10
// email('Kevin.Lapham@charlottecountyfl.gov', 'PAA.payment@accela.com', PAA Payment made for ' + capId + ' / ' + capIDString, 'PAA Payment made for ' + capId + ' / ' + capIDString);

