
// DISABLED: PRA:Building/Accessories/*/*:1
// if (currentUserID == 'LAPHAMK') {
// 	showMessage=true;
// 	showDebug = true;
//	} else {
// 	showMessage=false;
// 	showDebug = false;
// 	}

// DISABLED: PRA:Building/Accessories/*/*:7
// var LicProfList = getLicenseProfessional(capId);
// var x = 0;
// DISABLED: PRA:Building/Accessories/*/*:8
// if ((LicProfList.length > 0)) {
// 	for (x in LicProfList) if (LicProfList[x].printFlag == 'Y');
// 	lpIndex = x;
// 	}

// DISABLED: PRA:Building/Accessories/*/*:9
// if ((LicProfList.length > 0)) {
// 	var pLicNo = LicProfList[lpIndex].getLicenseNbr();
// 	}

// DISABLED: PRA:Building/Accessories/*/*:10
// if ((LicProfList.length > 0) && (pLicNo.substr(0, 3) == 'CGC') && (frACA == true)) {
// 	addStdCondition('CC PERMIT', 'Subcontractor Worksheet');
// 	}

