
// DISABLED: AffNoZon2:1
// if (currentUserID == 'LAPHAMK') {
// 	showMessage=true;
// 	showDebug=true;
//	} else {
// 	showMessage=false;
// 	showDebug=false;
// 	}

// DISABLED: AffNoZon2:16
// if (appMatch('Building/Accessories/Residential/RV Accessory Structure')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESRVACC');
// 	}

// DISABLED: AffNoZon2:17
// if (appMatch('Building/Construction/Commercial/DCA Office')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DCACOMM');
// 	}

// DISABLED: AffNoZon2:18
// if (appMatch('Building/Accessories/Residential/Seawall')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESSEAC');
// 	}

// DISABLED: AffNoZon2:19
// if (appMatch('Building/Accessories/Residential/Carport')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESCAR');
// 	}

// DISABLED: AffNoZon2:20
// if (appMatch('Building/Accessories/Commercial/Shed')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMSHED');
// 	}

// DISABLED: AffNoZon2:21
// if (appMatch('Building/Accessories/Commercial/Dock')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMDOCK');
// 	}

// DISABLED: AffNoZon2:22
// if (appMatch('Building/Accessories/Commercial/Cage')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMCAGE');
// 	}

// DISABLED: AffNoZon2:23
// if (appMatch('Building/Accessories/Commercial/Wall Exterior')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMWALLX');
// 	}

// DISABLED: AffNoZon2:24
// if (appMatch('Building/Accessories/Commercial/Slab')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMSLAB');
// 	}

// DISABLED: AffNoZon2:25
// if (appMatch('Building/Accessories/Residential/Wall Exterior')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESWALLX');
// 	}

// DISABLED: AffNoZon2:26
// if (appMatch('Building/Accessories/Commercial/Sign')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMSIGN');
// 	}

// DISABLED: AffNoZon2:27
// if (appMatch('Building/Accessories/Residential/Garage')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESGAR');
// 	}

// DISABLED: AffNoZon2:28
// if (appMatch('Building/Trade Permits/Residential/Fire')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-TRADEFIR');
// 	}

// DISABLED: AffNoZon2:29
// if (appMatch('Building/Construction/Residential/Mobile Home')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-MOBILE');
// 	}

// DISABLED: AffNoZon2:30
// if (appMatch('Building/Accessories/Residential/Baby Barrier')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-BABYBARRIER');
// 	}

// DISABLED: AffNoZon2:31
// if (appMatch('Building/Trade Permits/Commercial/Fire')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-TRADEFIR');
// 	}

// DISABLED: AffNoZon2:32
// if (appMatch('Building/Accessories/Commercial/Boatlift')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMBOAT');
// 	}

// DISABLED: AffNoZon2:33
// if (appMatch('Building/Accessories/Commercial/Lanai')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMLAN');
// 	}

// DISABLED: AffNoZon2:34
// if (appMatch('Planning/Growth Mgmt/DRC/NA')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DRC1');
// 	}

// DISABLED: AffNoZon2:35
// if (appMatch('Building/Accessories/Residential/Deck')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESDECK');
// 	}

// DISABLED: AffNoZon2:36
// if (appMatch('Building/Accessories/Residential/Swimming Pool')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESPOOL');
// 	}

// DISABLED: AffNoZon2:37
// if (appMatch('Building/Accessories/Residential/Cage')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESCAGE');
// 	}

// DISABLED: AffNoZon2:38
// if (appMatch('Building/Construction/Commercial/Build out')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMBO');
// 	}

// DISABLED: AffNoZon2:39
// if (appMatch('Building/Construction/Residential/Remodel')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESINREM');
// 	}

// DISABLED: AffNoZon2:40
// if (appMatch('Building/Accessories/Commercial/Outdoor Storage')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-STORAGE LOT');
// 	}

// DISABLED: AffNoZon2:41
// if (appMatch('Building/Accessories/Residential/Barn')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESBARN');
// 	}

// DISABLED: AffNoZon2:42
// if (appMatch('Building/Construction/Residential/Single Family')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-SINGFAM');
// 	}

// DISABLED: AffNoZon2:43
// if (appMatch('Building/Construction/Residential/Duplex')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DUPLEX');
// 	}

// DISABLED: AffNoZon2:44
// if (appMatch('Building/Construction/Commercial/Communication Tower')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMTOWER');
// 	}

// DISABLED: AffNoZon2:45
// if (appMatch('Building/Construction/Commercial/Shell')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMSHEL');
// 	}

// DISABLED: AffNoZon2:46
// if (appMatch('Building/Accessories/Commercial/Seawall')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMSEAC');
// 	}

// DISABLED: AffNoZon2:47
// if (appMatch('Building/Construction/Residential/Miscellaneous')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-MISCRES');
// 	}

// DISABLED: AffNoZon2:48
// if (appMatch('Building/Accessories/Residential/Boatlift')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESBOAT');
// 	}

// DISABLED: AffNoZon2:49
// if (appMatch('Planning/Growth Mgmt/Zoning Permits/Residential Fence')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESFENCE');
// 	}

// DISABLED: AffNoZon2:50
// if (appMatch('Building/Accessories/Commercial/Carport')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMCAR');
// 	}

// DISABLED: AffNoZon2:51
// if (appMatch('Building/Accessories/Residential/Fence')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESFENCE');
// 	}

// DISABLED: AffNoZon2:52
// if (appMatch('Building/Construction/Commercial/Multi-Family')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMMULTI');
// 	}

// DISABLED: AffNoZon2:53
// if (appMatch('Building/Construction/Commercial/Commercial Building')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMBLDG');
// 	}

// DISABLED: AffNoZon2:54
// if (appMatch('Building/Construction/Commercial/Foundation')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-FOUND');
// 	}

// DISABLED: AffNoZon2:55
// if (appMatch('Building/Accessories/Commercial/Swimming Pool')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMPOOL');
// 	}

// DISABLED: AffNoZon2:56
// if (appMatch('Building/Construction/Commercial/Modular')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DCACOMM');
// 	}

// DISABLED: AffNoZon2:57
// if (appMatch('Building/Accessories/Commercial/Wall Interior')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMWALLI');
// 	}

// DISABLED: AffNoZon2:58
// if (appMatch('Building/Construction/Residential/DCA Home')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DCARES');
// 	}

// DISABLED: AffNoZon2:59
// if (appMatch('Building/Accessories/Commercial/Deck')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMDECK');
// 	}

// DISABLED: AffNoZon2:60
// if (appMatch('Building/Construction/Residential/Modular')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-MOBILE');
// 	}

// DISABLED: AffNoZon2:61
// if (appMatch('Building/Construction/Commercial/Change of Occupancy')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMCHG');
// 	}

// DISABLED: AffNoZon2:62
// if (appMatch('Building/Accessories/Commercial/Garage')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMGAR');
// 	}

// DISABLED: AffNoZon2:63
// if (appMatch('Building/Construction/Residential/Townhouse')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-TOWN');
// 	}

// DISABLED: AffNoZon2:64
// if (appMatch('Building/Accessories/Residential/Canopy')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESCAN');
// 	}

// DISABLED: AffNoZon2:65
// if (appMatch('Building/Construction/Residential/Addition')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESADD');
// 	}

// DISABLED: AffNoZon2:66
// if (appMatch('Building/Accessories/Residential/Mobile Home Addition')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESADD');
// 	}

// DISABLED: AffNoZon2:67
// if (appMatch('Building/Accessories/Residential/Shed')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESSHED');
// 	}

// DISABLED: AffNoZon2:68
// if (appMatch('Building/Accessories/Residential/Slab')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESSLAB');
// 	}

// DISABLED: AffNoZon2:69
// if (appMatch('Planning/Growth Mgmt/Site Plan Review/Site Plan Review')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-DRC1');
// 	}

// DISABLED: AffNoZon2:70
// if (appMatch('Building/Construction/Commercial/Miscellaneous')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMMISC');
// 	}

// DISABLED: AffNoZon2:71
// if (appMatch('Building/Construction/Commercial/Remodel')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMINREM');
// 	}

// DISABLED: AffNoZon2:72
// if (appMatch('Planning/Land Development/Plats/Subdivision Variance')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-SUBDVAR_REVIEWS');
// 	}

// DISABLED: AffNoZon2:73
// if (appMatch('Building/Construction/Commercial/Building-Babcock')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMBLDG_B');
// 	}

// DISABLED: AffNoZon2:74
// if (appMatch('Building/Accessories/Commercial/Fence')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMFENC');
// 	}

// DISABLED: AffNoZon2:75
// if (appMatch('Building/Accessories/Residential/Lanai')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESLANAI');
// 	}

// DISABLED: AffNoZon2:76
// if (appMatch('Planning/Land Development/Plats/Minor Subdivision')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-MINORSUBDIVISIONREVIEWS');
// 	}

// DISABLED: AffNoZon2:77
// if (appMatch('Building/Accessories/Residential/Dock')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-RESDOCK');
// 	}

// DISABLED: AffNoZon2:78
// if (appMatch('Building/Construction/Commercial/Addition')) {
// 	closeTask('Zoning', 'Not Required', 'Automated by document', '', 'PR-COMMADD');
// 	}

