
// DISABLED: ASB:Building/*/*/*:5
// if (!appMatch('Building/POS/*/*') && !appMatch('Building/Land Development/ROW/*')) {
// 	var LicProfList = aa.env.getValue('LicProfList').toArray();
// 	var x=0;
// 	}

// DISABLED: ASB:Building/*/*/*:6
// if (!appMatch('Building/POS/*/*') && !appMatch('Building/Land Development/ROW/*') && (LicProfList.length > 0 )) {
// 	for(x in LicProfList) comment(GetLicInfo(LicProfList[x].getLicenseNbr()));
// 	}

// DISABLED: ASB:Building/*/*/*:10
// if (!appMatch('Building/Land Development/ROW/*') && !appMatch('Building/POS/*/*') && LPValidation()) {
// 	showMessage=true;
// 	cancel=true;
// 	comment('Your General liability or Workmans Compensation Insurance is expired or not on file. Please contact Community Development on 941-743-1201');
// 	}

