
// DISABLED: CC_350_WFUpdateAfter:1
// if (appMatch('Building/*/*/*')) {
// 	br_nch('CC_351_BLD_WFUpdateAfter');
// 	}

// DISABLED: CC_350_WFUpdateAfter:2
// if (appMatch('CodeEnforcement/*/*/*')) {
// 	br_nch('CC_351_CE_WFUpdateAfter');
// 	}

// DISABLED: CC_350_WFUpdateAfter:3
// if (appMatch('Planning/Managed Growth/*/*')) {
// 	br_nch('CC_351_GM_WFUpdateAfter');
// 	}

// DISABLED: CC_350_WFUpdateAfter:4
// if (appMatch('Planning/Land Development/*/*')) {
// 	br_nch('CC_351_LD_WFUpdateAfter');
// 	}

// DISABLED: CC_350_WFUpdateAfter:5
// if (appMatch('Licenses/*/*/*')) {
// 	br_nch('CC_351_LIC_WFUpdateAfter');
// 	}

// DISABLED: CC_350_WFUpdateAfter:6
// comment('CC_350_WFUpdateAfter executed successfully');

