
// DISABLED: CC_300_WFUpdateBefore:1
// if (appMatch('Building/*/*/*')) {
// 	br_nch('CC_301_BLD_WFUpdateBefore');
// 	}

// DISABLED: CC_300_WFUpdateBefore:2
// if (appMatch('CodeEnforcement/*/*/*')) {
// 	br_nch('CC_301_CE_WFUpdateBefore');
// 	}

// DISABLED: CC_300_WFUpdateBefore:3
// if (appMatch('Planning/Managed Growth/*/*')) {
// 	br_nch('CC_301_GM_WFUpdateBefore');
// 	}

// DISABLED: CC_300_WFUpdateBefore:4
// if (appMatch('Planning/Land Development/*/*')) {
// 	br_nch('CC_301_LD_WFUpdateBefore');
// 	}

// DISABLED: CC_300_WFUpdateBefore:5
// if (appMatch('Licenses/*/*/*')) {
// 	br_nch('CC_301_LIC_WFUpdateBefore');
// 	}

// DISABLED: CC_300_WFUpdateBefore:6
// comment('CC_300_WFUpdateBefore executed successfully');

