
// DISABLED: CC_301_CE_WFUpdateBefore:1
// comment('CC_301_CE_WFUpdateBefore Executing message');
// BLDcomm = 'Created from CAP # ' + capIDString;
// DISABLED: CC_301_CE_WFUpdateBefore:2
// if (appMatch('CodeEnforcement/Complaints/*/*') && wfStatus == 'Not in Compliance'  && wfTask == 'Code Violation' && AInfo['Updated.CILB'] != 'CHECKED' && AInfo['Updated.CE'] != 'CHECKED'  && AInfo['Updated.Unsafe Building'] != 'CHECKED') {
// 	showDebug = false;
// DISABLED: CC_301_CE_WFUpdateBefore:3
// 	showMessage = false;
// 	message='If Not in Compliance status selected, please check CE, CILB or Unsafe Building ';
// 	showMessage = true;
// 	cancel = true;
// 	}

