
// DISABLED: CC_301_BLD_WFUpdateBefore:1
// comment('CC_301_BLD_WFUpdateBefore Executing message');
// DISABLED: CC_301_BLD_WFUpdateBefore:2
// if (wfTask == 'Finaled' && wfStatus == ['Finaled','C of O Issued','C of Completion Issued'] && !balanceDue == 0) {
// 	showDebug = false;
// DISABLED: CC_301_BLD_WFUpdateBefore:3
// 	showMessage = false;
// 	message='All Fees must be paid before this action can take place.';
// 	showMessage = true;
// 	}

