
// DISABLED: CC_351_CE_WFUpdateAfter:1
// comment('CC_351_CE_WFUpdateAfter Executing message');
// BLDcomm = 'Created from CAP # ' + capIDString;
// DISABLED: CC_351_CE_WFUpdateAfter:2
// if (appMatch('CodeEnforcement/Complaints/*/*') && wfTask == 'Code Violation' && wfStatus == 'Not in Compliance' && AInfo['CILB'] == 'C') {
// 	newAppID=createChild('CodeEnforcement','CILB','NA','NA',BLDcomm);
// DISABLED: CC_351_CE_WFUpdateAfter:3
// 	altid = newAppID.getCustomID();
// 	}

// DISABLED: CC_351_CE_WFUpdateAfter:4
// if (appMatch('CodeEnforcement/Complaints/*/*') && wfTask == 'Code Violation' && wfStatus == 'Not in Compliance' && AInfo['CE'] == 'C') {
// 	newAppID=createChild('CodeEnforcement','Code Enforcement','NA','NA',BLDcomm);
// DISABLED: CC_351_CE_WFUpdateAfter:5
// 	altid = newAppID.getCustomID();
// 	}

// DISABLED: CC_351_CE_WFUpdateAfter:6
// if (appMatch('CodeEnforcement/Complaints/*/*') && wfTask == 'Code Violation' && wfStatus == 'Not in Compliance' && AInfo['Unsafe Building'] == 'C') {
// 	newAppID=createChild('CodeEnforcement','Unsafe Building','NA','NA',BLDcomm);
// DISABLED: CC_351_CE_WFUpdateAfter:7
// 	altid = newAppID.getCustomID();
// 	}

