
if (currentUserID == 'LAPHAMK') {
	showMessage=true;
	showDebug = true;
	} else {
	showMessage=true;
	showDebug = false;
	}

// DISABLED: PPA:Building/*/*/*:5
// if (checkMEXTEND(capIDString) == true) {
// 	editAppSpecific('Expiration Date', dateAdd(AInfo[' Expiration Date '], 90));
// 	updateAppStatus('Issued', '');
// 	comment('90-Days added to expiration date.');
// DISABLED: PPA:Building/*/*/*:6
// 	email('Kevin.Lapham@charlottecountyfl.gov', 'MEXTEND.payment@accela.com', 'M-EXTEND PPA Payment made for ' + capId + ' / ' + capIDString, 'M-EXTEND PPA Payment made for ' + capId + ' / ' + capIDString);
// 	}

