
if (currentUserID == 'LAPHAMK') {
	showMessage=true;
	showDebug = true;
	} else {
	showMessage=false;
	showDebug = false;
	}

// DISABLED: PRA:Building/Trade Permits/*/*:10
// var LicProfList = getLicenseProfessional(capId);
// var x = 0;
// DISABLED: PRA:Building/Trade Permits/*/*:11
// if ((LicProfList.length > 0)) {
// 	for (x in LicProfList) if (LicProfList[x].printFlag == 'Y');
// 	lpIndex = x;
// 	}

// DISABLED: PRA:Building/Trade Permits/*/*:12
// if ((LicProfList.length > 0)) {
// 	var pLicNo = LicProfList[lpIndex].getLicenseNbr();
// 	}

// DISABLED: PRA:Building/Trade Permits/*/*:13
// if ((LicProfList.length > 0) && (pLicNo.substr(0, 3) == 'CGC') && (frACA == true)) {
// 	addStdCondition('CC PERMIT', 'Subcontractor Worksheet');
// 	}

